eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: recipes
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/recipes/**
        - id: ingredients
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/ingredients/**
